export const alphaKeys = {
  'a': true,
  'b': true,
  'c': true,
  'd': true,
  'e': true,
  'f': true,
  'g': true,
  'h': true,
  'i': true,
  'j': true,
  'k': true,
  'l': true,
  'm': true,
  'n': true,
  'o': true,
  'p': true,
  'q': true,
  'r': true,
  's': true,
  't': true,
  'u': true,
  'v': true,
  'w': true,
  'x': true,
  'y': true,
  'z': true,
}
//======================================================
export const numericKeys = {
  '1': true,
  '2': true,
  '3': true,
  '4': true,
  '5': true,
  '6': true,
  '7': true,
  '8': true,
  '9': true,
  '0': true,
}
//======================================================
export const backgroundImages = [
  './images/brown-wood-table.jpeg',
  './images/fabric.jpg',
  './images/wood1.jpg',
  './images/wood2.jpg',
  './images/wood3.jpg',
  './images/wood4.jpg',
  './images/wood5.jpg',
  './images/wood6.jpg',
]